<a href="https://colab.research.google.com/github/sairaawahid/Data-Science-in-Python-Data-Prep-and-EDA/blob/main/Exploratory%20Data%20Analysis/Exploratory_data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exploratory Data Analysis
**Methods/functions practiced for exploratory data analysis:**
1.  `loc[]` with logical conditions

**Datasets:**
1.  groceries_with_new_columns.pkl

## 1. Filtering

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np

In [3]:
groceries = pd.read_pickle('/content/drive/MyDrive/Data Science in Pyhton by Maven Analytics/1. Data Prep & EDA/Data/groceries_with_new_columns.pkl')
groceries.head()

,Product_ID,Product_ID_NUM,Category,Subcategory,Item,Organic,Price_Dollars,Inventory,Percent Inventory,Low Inventory,Last_Updated,Last_Updated_Time,Next_Scheduled_Shipment,Shipment_Date_DOW
0,P100010,100010,Produce,Fruit,Apple,False,1.50,349,7.19,,2023-06-12 15:35:00,15:35:00,2023-06-15,Thursday
1,P100011,100011,Produce,Fruit,Banana,False,0.40,500,10.29,,2023-06-12 18:30:00,18:30:00,2023-06-15,Thursday
2,P100012,100012,Produce,Fruit,Grapes,False,4.00,200,4.12,,2023-06-12 17:22:00,17:22:00,2023-06-15,Thursday
3,P100013,100013,Produce,Fruit,Grapefruit,False,0.99,50,1.03,,2023-06-12 16:29:00,16:29:00,2023-06-15,Thursday
4,P100014,100014,Produce,Fruit,Organic Strawberries,True,3.99,148,3.05,,2023-06-12 18:10:00,18:10:00,2023-06-15,Thursday

In [5]:
# Only filter on low inventory rows
groceries[groceries['Low Inventory'] == 'Low inventory']

,Product_ID,Product_ID_NUM,Category,Subcategory,Item,Organic,Price_Dollars,Inventory,Percent Inventory,Low Inventory,Last_Updated,Last_Updated_Time,Next_Scheduled_Shipment,Shipment_Date_DOW
15,P100025,100025,Produce,Dairy,Milk (Soy),False,4.49,32,0.66,Low inventory,2023-06-13 08:37:00,08:37:00,2023-06-17,Saturday
17,P100027,100027,Pantry,Snacks,Apple Sauce - organic,True,1.50,27,0.56,Low inventory,2023-06-10 12:02:00,12:02:00,2023-06-24,Saturday
20,P100030,100030,Pantry,Snacks,Raisins,False,2.99,5,0.10,Low inventory,2023-06-10 12:38:00,12:38:00,2023-06-24,Saturday

In [7]:
# Filter on both rows and column using .loc[]
# Create a list to filter more than 1 column
groceries.loc[groceries['Low Inventory'] == 'Low inventory', ['Price_Dollars', 'Inventory']]

    Price_Dollars  Inventory
15           4.49         32
17           1.50         27
20           2.99          5

In [8]:
# Filter on the snacks subcategory
groceries[groceries.Subcategory == 'Snacks']

# No output??

Empty DataFrame
Columns: [Product_ID, Product_ID_NUM, Category, Subcategory, Item, Organic, Price_Dollars, Inventory, Percent Inventory, Low Inventory, Last_Updated, Last_Updated_Time, Next_Scheduled_Shipment, Shipment_Date_DOW]
Index: []

In [9]:
# Check one value
groceries.Subcategory[0]

' Fruit'

In [11]:
# Strip the blank space then filter
groceries.Subcategory = groceries.Subcategory.str.strip()

In [12]:
# Filter on the snacks subcategory
groceries[groceries.Subcategory == 'Snacks']

,Product_ID,Product_ID_NUM,Category,Subcategory,Item,Organic,Price_Dollars,Inventory,Percent Inventory,Low Inventory,Last_Updated,Last_Updated_Time,Next_Scheduled_Shipment,Shipment_Date_DOW
17,P100027,100027,Pantry,Snacks,Apple Sauce - organic,True,1.50,27,0.56,Low inventory,2023-06-10 12:02:00,12:02:00,2023-06-24,Saturday
18,P100028,100028,Pantry,Snacks,Chips,False,2.50,365,7.51,,2023-06-10 12:12:00,12:12:00,2023-06-24,Saturday
19,P100029,100029,Pantry,Snacks,Cookies (Oatmeal),False,5.39,340,7.00,,2023-06-10 12:24:00,12:24:00,2023-06-24,Saturday
20,P100030,100030,Pantry,Snacks,Raisins,False,2.99,5,0.10,Low inventory,2023-06-10 12:38:00,12:38:00,2023-06-24,Saturday

In [13]:
# Filter on low inventory snacks
mask = (groceries['Low Inventory'] == 'Low inventory') & (groceries.Subcategory == 'Snacks')
groceries[mask]

,Product_ID,Product_ID_NUM,Category,Subcategory,Item,Organic,Price_Dollars,Inventory,Percent Inventory,Low Inventory,Last_Updated,Last_Updated_Time,Next_Scheduled_Shipment,Shipment_Date_DOW
17,P100027,100027,Pantry,Snacks,Apple Sauce - organic,True,1.50,27,0.56,Low inventory,2023-06-10 12:02:00,12:02:00,2023-06-24,Saturday
20,P100030,100030,Pantry,Snacks,Raisins,False,2.99,5,0.10,Low inventory,2023-06-10 12:38:00,12:38:00,2023-06-24,Saturday

In [14]:
# Filter rows and columns
groceries.loc[mask, ['Subcategory', 'Item', 'Inventory']]

   Subcategory                   Item  Inventory
17      Snacks  Apple Sauce - organic         27
20      Snacks                Raisins          5