<a href="https://colab.research.google.com/github/sairaawahid/Data-Science-in-Python-Data-Prep-and-EDA/blob/main/Gathering%20Data/Gathering_data_course_offerings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Gathering Data

**Methods/functions practiced for gathering data:**
1.   `pd.read_csv`
2.   `pd.read_excel`
3.   `pd.read_sql`
4.   `head()`
5.   `tail()`
6.   `shape`
7.   `describe()`
8.   `info()`

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

## 1. Reading Flat Files

### a. The basics

In [ ]:
import pandas as pd

In [ ]:
pd.read_csv('/content/drive/MyDrive/Data Science in Pyhton by Maven Analytics/1. Data Prep & EDA/Data/course_offerings.csv')

   course_id                  course_name    instructor
0        101              Intro to Python  Chris Bruehl
1        102                 Intro to SQL   John Pauler
2        201    Exploratory Data Analysis    Alice Zhao
3        301                   Algorithms  Chris Bruehl
4        331  Natural Language Processing    Alice Zhao

### b. How to change the arguments

In [ ]:
# Tweak the header argument
pd.read_csv('/content/drive/MyDrive/Data Science in Pyhton by Maven Analytics/1. Data Prep & EDA/Data/course_offerings.csv', header=None)
# header = None --- reads column name/header row as first data row

           0                            1             2
0  course_id                  course_name    instructor
1        101              Intro to Python  Chris Bruehl
2        102                 Intro to SQL   John Pauler
3        201    Exploratory Data Analysis    Alice Zhao
4        301                   Algorithms  Chris Bruehl
5        331  Natural Language Processing    Alice Zhao

In [ ]:
# Tweak the sep argument
pd.read_csv('/content/drive/MyDrive/Data Science in Pyhton by Maven Analytics/1. Data Prep & EDA/Data/course_offerings.csv', sep=',')
# pd.read_csv('../Data/course_offerings.csv', sep = '|')

   course_id                  course_name    instructor
0        101              Intro to Python  Chris Bruehl
1        102                 Intro to SQL   John Pauler
2        201    Exploratory Data Analysis    Alice Zhao
3        301                   Algorithms  Chris Bruehl
4        331  Natural Language Processing    Alice Zhao

## 2. Reading Excel Files

In [ ]:
# The basics
pd.read_excel('/content/drive/MyDrive/Data Science in Pyhton by Maven Analytics/1. Data Prep & EDA/Data/Course Offerings.xlsx')

     Instructor                    Title
0  Chris Bruehl   Lead Python Instructor
1   John Pauler     Chief Growth Officer
2    Alice Zhao  Data Science Instructor

In [ ]:
# Tweak the sheet_name argument
pd.read_excel('/content/drive/MyDrive/Data Science in Pyhton by Maven Analytics/1. Data Prep & EDA/Data/Course Offerings.xlsx', sheet_name=1)

   Course ID                  Course Name    Instructor
0        101              Intro to Python  Chris Bruehl
1        102                 Intro to SQL   John Pauler
2        201    Exploratory Data Analysis    Alice Zhao
3        301                   Algorithms  Chris Bruehl
4        331  Natural Language Processing    Alice Zhao

In [ ]:
# Tweak the header argument
pd.read_excel('/content/drive/MyDrive/Data Science in Pyhton by Maven Analytics/1. Data Prep & EDA/Data/Course Offerings.xlsx', sheet_name=1, header=None)

           0                            1             2
0  Course ID                  Course Name    Instructor
1        101              Intro to Python  Chris Bruehl
2        102                 Intro to SQL   John Pauler
3        201    Exploratory Data Analysis    Alice Zhao
4        301                   Algorithms  Chris Bruehl
5        331  Natural Language Processing    Alice Zhao

## 3. Connecting to a SQL Database

In [ ]:
# Connect to a SQLite database

import sqlite3
conn = sqlite3.connect('/content/drive/MyDrive/Data Science in Pyhton by Maven Analytics/1. Data Prep & EDA/Data/maven.db')
pd.read_sql('SELECT * FROM courses', conn)

   course_id                       course    instructor
0        101              Intro to Python  Chris Bruehl
1        102                 Intro to SQL   John Pauler
2        201    Exploratory Data Analysis    Alice Zhao
3        301                   Algorithms  Chris Bruehl
4        331  Natural Language Processing    Alice Zhao

In [ ]:
pd.read_sql('SELECT * FROM courses WHERE course_id = 102', conn)

   course_id        course   instructor
0        102  Intro to SQL  John Pauler

In [ ]:
# Another example of a SQL query
pd.read_sql('SELECT * FROM courses WHERE course_id LIKE "2%"', conn)

   course_id                     course  instructor
0        201  Exploratory Data Analysis  Alice Zhao

## 4. Quickly Explore a DataFrame

In [ ]:
# Save the output as a DataFrame

df = pd.read_csv('/content/drive/MyDrive/Data Science in Pyhton by Maven Analytics/1. Data Prep & EDA/Data/course_offerings.csv')
df

   course_id                  course_name    instructor
0        101              Intro to Python  Chris Bruehl
1        102                 Intro to SQL   John Pauler
2        201    Exploratory Data Analysis    Alice Zhao
3        301                   Algorithms  Chris Bruehl
4        331  Natural Language Processing    Alice Zhao

In [ ]:
df.head(3)

   course_id                course_name    instructor
0        101            Intro to Python  Chris Bruehl
1        102               Intro to SQL   John Pauler
2        201  Exploratory Data Analysis    Alice Zhao

In [ ]:
df.tail(2)

   course_id                  course_name    instructor
3        301                   Algorithms  Chris Bruehl
4        331  Natural Language Processing    Alice Zhao

In [ ]:
df.shape

(5, 3)

In [ ]:
df.count()

course_id      5
course_name    5
instructor     5
dtype: int64

In [ ]:
df.describe()

        course_id
count    5.000000
mean   207.200000
std    107.829495
min    101.000000
25%    102.000000
50%    201.000000
75%    301.000000
max    331.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   course_id    5 non-null      int64
 1   course_name  5 non-null      object
 2   instructor   5 non-null      object
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes